name: auto-ci-builds

on:
  - push
  - pull_request

jobs:
  build_macOS-latest:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: install build dependencies
      run: |
        ./build/install-deps-macos.sh
    - name: check mono version
      run: |
        mono --version
    - name: run autogen
      run: |
        ./autogen.sh
    - name: build
      run: |
        make

# TODO:
#  macOS_tests_unit:
#    runs-on: macOS-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Run unit test
#      run: |
#        ./build/install-deps-macos.sh
#        ./autogen.sh && make && make check
#

  build_Ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install build dependencies from debian/control
      run: |
        sudo apt update > /dev/null
        sudo apt install --yes devscripts equivs > /dev/null
        sudo mk-build-deps --install debian/control > /dev/null
        sudo apt install --yes ./smuxi-build-deps_*.deb
    - name: check mono version
      run: |
        mono --version
    - name: autogen and configure
      run: |
        ./autogen.sh
    - name: build
      run: |
        make
